Description: >
  This CloudFormation template defines resources for configuring an AWS ElastiCache Redis cluster. 
  It includes a security group for the cluster, a subnet group, and a replication group. 
  The security group named "MemCache" is set up to allow incoming traffic on port 6379 for a specific IP range. 
  The subnet group, named "DefaultApplication," specifies the subnets where the cluster will be deployed. 
  The replication group, named "Application replication group," describes the Redis cluster's properties, such as node type, maintenance window, and snapshot settings.
  
  - VpcId: !ImportValue Network:ApplicationVPC imports the values from the file "/VPC/network.yml"


Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Security group for Redis cluster
      GroupName: MemCache
      SecurityGroupIngress:
        - CidrIp: 10.0.0.0/8
          FromPort: 6379
          ToPort: 6379
          IpProtocol: tcp
      VpcId: !ImportValue Network:ApplicationVPC

  SubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties:
      Description: Default Subnet Group for the application
      CacheSubnetGroupName: DefaultApplication
      SubnetIds:
        - !ImportValue Network:ApplicationPrivateWithoutNATSubnet1
        - !ImportValue Network:ApplicationPrivateWithoutNATSubnet2
        - !ImportValue Network:ApplicationPrivateWithoutNATSubnet3

  ReplicationGroup:
    Type: "AWS::ElastiCache::ReplicationGroup"
    Properties:
      AutomaticFailoverEnabled: true
      CacheNodeType: cache.t2.micro
      CacheSubnetGroupName: !Ref SubnetGroup
      Engine: redis
      NumCacheClusters: 2
      Port: 6379
      PreferredMaintenanceWindow: sun:22:00-sun:23:30
      ReplicationGroupDescription: Application replication group
      SecurityGroupIds:
        - !GetAtt
          - SecurityGroup
          - GroupId
      SnapshotRetentionLimit: 7
      SnapshotWindow: "05:00-09:00"
