
AWSTemplateFormatVersion: '2010-09-09'
Description: "This AWS CloudFormation Template creates an Amazon SQS dead-letter queue\
  \ (DLQ) and an Amazon SNS topic associated with the DLQ.\n"
Resources:
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: dlq1
  Topic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: dlq1
Outputs:
  DeadLetterQueue:
    Description: DLQ ARN
    Value:
      Fn::GetAtt:
      - DeadLetterQueue
      - Arn
    Export:
      Name:
        Fn::Join:
        - ':'
        - - Ref: AWS::StackName
          - DeadLetterQueue
