Description: IAM role for ECS tasks in a Fargate cluster. Grants permissions for auto-scaling and monitoring. 
     
Resources:
  FargateAutoScalingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: FargateAutoScalingRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecs:DescribeServices
                  - ecs:UpdateService
                  - cloudwatch:DeleteAlarms
                  - cloudwatch:DescribeAlarms
                  - cloudwatch:PutMetricAlarm
                Resource: "*"

Outputs:
  Loadbalancer:
    Description: Role ARN for the FargateAutoScalingRole
    Value: !GetAtt FargateAutoScalingRole.Arn
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", FargateAutoScalingRole]]
